#!/usr/bin/env python3
"""Interactively select a rectangular manual crop and save it as a sidecar."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Iterable

import yaml
from PIL import Image, ImageTk

from prepare_sketches import (
    load_config,
    load_override,
    override_path,
    read_oriented_rgb,
    rotate_clockwise,
    validate_manual_bounds,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Select and save a manual rectangular sketch crop.")
    parser.add_argument("input", type=Path, help="Source photograph")
    parser.add_argument(
        "--config",
        type=Path,
        default=Path(__file__).with_name("config.yaml"),
        help="Shared sketch-prep configuration",
    )
    parser.add_argument(
        "--rotation",
        type=int,
        choices=(0, 90, 180, 270),
        help="Clockwise rotation; defaults to the existing override or zero",
    )
    parser.add_argument(
        "--bounds",
        type=int,
        nargs=4,
        metavar=("LEFT", "TOP", "RIGHT", "BOTTOM"),
        help="Save exact bounds without opening the interactive editor",
    )
    return parser.parse_args()


def write_manual_override(path: Path, rotation: int, bounds: Iterable[int]) -> None:
    data = {
        "mode": "manual",
        "rotation_degrees_clockwise": int(rotation),
        "bounds": [int(value) for value in bounds],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("# Generated by manual_crop.py. Coordinates are measured after rotation.\n")
        yaml.safe_dump(data, handle, sort_keys=False)
    os.replace(temporary, path)


class CropEditor:
    def __init__(self, source: Path, config: dict, rotation: int, existing_bounds: Iterable[int] | None):
        import tkinter as tk
        from tkinter import messagebox

        self.tk = tk
        self.messagebox = messagebox
        self.source = source
        self.config = config
        self.rotation = rotation
        self.base_image = read_oriented_rgb(source)
        self.bounds = tuple(existing_bounds) if existing_bounds is not None else None
        self.drag_start: tuple[int, int] | None = None
        self.rectangle_id: int | None = None
        self.photo = None

        self.root = tk.Tk()
        self.root.title(f"Manual sketch crop — {source.name}")
        self.root.minsize(720, 520)

        toolbar = tk.Frame(self.root, padx=10, pady=8)
        toolbar.pack(fill=tk.X)
        tk.Label(toolbar, text="Drag around the sketch. Keep every intentional mark inside the blue rectangle.").pack(
            side=tk.LEFT, expand=True, anchor="w"
        )
        tk.Button(toolbar, text="Rotate 90°", command=self.rotate).pack(side=tk.LEFT, padx=4)
        tk.Button(toolbar, text="Reset", command=self.reset).pack(side=tk.LEFT, padx=4)
        tk.Button(toolbar, text="Save crop", command=self.save).pack(side=tk.LEFT, padx=4)

        self.canvas = tk.Canvas(self.root, background="#18252e", cursor="crosshair", highlightthickness=0)
        self.canvas.pack(fill=tk.BOTH, expand=True)
        self.status = tk.StringVar()
        tk.Label(self.root, textvariable=self.status, anchor="w", padx=10, pady=6).pack(fill=tk.X)

        self.canvas.bind("<ButtonPress-1>", self.start_drag)
        self.canvas.bind("<B1-Motion>", self.drag)
        self.canvas.bind("<ButtonRelease-1>", self.end_drag)
        self.root.bind("<Return>", lambda _event: self.save())
        self.root.bind("<Escape>", lambda _event: self.root.destroy())
        self.root.after(50, self.render)

    def oriented_image(self) -> Image.Image:
        return Image.fromarray(rotate_clockwise(self.base_image, self.rotation))

    def render(self) -> None:
        image = self.oriented_image()
        max_width = max(640, self.root.winfo_width() - 24)
        max_height = max(420, self.root.winfo_height() - 110)
        self.scale = min(max_width / image.width, max_height / image.height, 1.0)
        display_size = (max(1, round(image.width * self.scale)), max(1, round(image.height * self.scale)))
        preview = image.resize(display_size, Image.Resampling.LANCZOS)
        self.photo = ImageTk.PhotoImage(preview)
        self.canvas.configure(width=display_size[0], height=display_size[1], scrollregion=(0, 0, *display_size))
        self.canvas.delete("all")
        self.canvas.create_image(0, 0, image=self.photo, anchor="nw")
        self.rectangle_id = None
        if self.bounds is not None:
            self.draw_rectangle(tuple(round(value * self.scale) for value in self.bounds))
        self.update_status()

    def clamped_point(self, x: int, y: int) -> tuple[int, int]:
        width = round(self.oriented_image().width * self.scale)
        height = round(self.oriented_image().height * self.scale)
        return max(0, min(x, width)), max(0, min(y, height))

    def draw_rectangle(self, bounds: tuple[int, int, int, int]) -> None:
        if self.rectangle_id is not None:
            self.canvas.delete(self.rectangle_id)
        self.rectangle_id = self.canvas.create_rectangle(*bounds, outline="#1db5d9", width=4)

    def start_drag(self, event) -> None:
        self.drag_start = self.clamped_point(event.x, event.y)

    def drag(self, event) -> None:
        if self.drag_start is None:
            return
        current = self.clamped_point(event.x, event.y)
        self.draw_rectangle((*self.drag_start, *current))

    def end_drag(self, event) -> None:
        if self.drag_start is None:
            return
        end = self.clamped_point(event.x, event.y)
        left, right = sorted((self.drag_start[0], end[0]))
        top, bottom = sorted((self.drag_start[1], end[1]))
        self.bounds = (
            round(left / self.scale),
            round(top / self.scale),
            round(right / self.scale),
            round(bottom / self.scale),
        )
        self.drag_start = None
        self.update_status()

    def update_status(self) -> None:
        if self.bounds is None:
            message = f"Rotation: {self.rotation}° clockwise — no crop selected"
        else:
            message = f"Rotation: {self.rotation}° clockwise — bounds: {list(self.bounds)}"
        self.status.set(message + " — Enter saves; Esc cancels")

    def rotate(self) -> None:
        self.rotation = (self.rotation + 90) % 360
        self.bounds = None
        self.render()

    def reset(self) -> None:
        self.bounds = None
        self.render()

    def save(self) -> None:
        if self.bounds is None:
            self.messagebox.showerror("No crop selected", "Drag a rectangle around the sketch before saving.")
            return
        image = self.oriented_image()
        try:
            bounds = validate_manual_bounds(self.bounds, image.width, image.height)
        except ValueError as error:
            self.messagebox.showerror("Invalid crop", str(error))
            return
        destination = override_path(self.config, self.source)
        write_manual_override(destination, self.rotation, bounds)
        self.messagebox.showinfo("Crop saved", f"Saved {destination}\n\nRerun prepare_sketches.py with --force.")
        self.root.destroy()

    def run(self) -> None:
        self.root.mainloop()


def main() -> int:
    args = parse_args()
    source = args.input.resolve()
    if not source.is_file():
        raise FileNotFoundError(source)
    config = load_config(args.config)
    existing = load_override(config, source)
    rotation = args.rotation if args.rotation is not None else int(existing.get("rotation_degrees_clockwise", 0))
    oriented = rotate_clockwise(read_oriented_rgb(source), rotation)

    if args.bounds is not None:
        bounds = validate_manual_bounds(args.bounds, oriented.shape[1], oriented.shape[0])
        destination = override_path(config, source)
        write_manual_override(destination, rotation, bounds)
        print(f"Saved manual crop to {destination}")
        return 0

    existing_bounds = existing.get("bounds") if existing.get("mode") == "manual" else None
    CropEditor(source, config, rotation, existing_bounds).run()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

